id: A5A8C570B
base_file: fFBB9.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.138472
  last_modified_at: 2022-05-30 20:37:16.138479
