id: A5A8C570B
base_file: f07B4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.079665
  last_modified_at: 2022-05-30 20:37:16.079670
