id: A5A8C570B
base_file: fBC74.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.123561
  last_modified_at: 2022-05-30 20:37:16.123565
