id: A5A8C570B
base_file: f7A78.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.103980
  last_modified_at: 2022-05-30 20:37:16.104004
