id: A5A8C570B
base_file: f49A0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.093641
  last_modified_at: 2022-05-30 20:37:16.093643
