id: A5A8C570B
base_file: fA072.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.108660
  last_modified_at: 2022-05-30 20:37:16.108666
