id: A5A8C570B
base_file: fAF25.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.119770
  last_modified_at: 2022-05-30 20:37:16.119775
