id: A5A8C570B
base_file: f0E01.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.082426
  last_modified_at: 2022-05-30 20:37:16.082429
