id: A5A8C570B
base_file: fA0E4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.110591
  last_modified_at: 2022-05-30 20:37:16.110597
