id: A5A8C570B
base_file: f020D.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:37:16.074748
  last_modified_at: 2022-05-30 20:37:16.074758
